services:
  app:
    build: .
    container_name: chat_app_fe
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./node_modules:/usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - chat_app_network
networks:
  chat_app_network:
    driver: bridge
